import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Center } from '@/components/Center'
import { Description } from '@/components/Description'
import { Footer } from '@/components/Footer'
import { Headline } from '@/components/Headline'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Headline title="About Page"/>

        <Description page="about.js"/>
        <Center />
        <Footer />
      </main>
    </>
  )
}
